config/routes.rb
Plg::Application.routes.draw do
  resources :employees

  root :to => 'home#index'
  match "home" => "home#index"
  match "attorneys" => "attorneys#index"
  match "locations" => "locations#index"
  match "contact" => "contact#index"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  def full_name
    "#{self.first_name} #{self.middle_name}. #{self.last_name}"
  end
  
  def initials
    "#{self.first_name[0]}#{self.middle_name[0]}#{self.last_name[0]}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attorneys_controller.rb
class AttorneysController < ApplicationController
  def index
    @employees = Employee.find(:all, :order => 'display_order') 
  end
  
  def show
    @employee = Employee(params[:id])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @employees = Employee.find(:all, :order => 'display_order') 
  end
  
  def show
    @employee = Employee(params[:id])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.find(:all, :order => 'display_order') 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attorneys_helper.rb
module AttorneysHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/attorneys/index.html.erb
<% content_for :title do %>
	Attorneys
<% end %>

<div id="employee_list">
<% @employees.each do |employee| %>
	<div class="employee">
		<div class="photo">
			<%= image_tag ('biopics/' + employee.initials.downcase + 'thumb.jpg') %>
		</div>
		<div class="short_bio">
			<div class="name">
				<%= employee.full_name %>
			</div>
			<%= employee.short_bio %> <span class="full_bio"><%= raw employee.full_bio %></span></br><a class="link_to_full_bio">More...</a>
		</div>
	</div>
<% end %>
</div>

app/views/contact/index.html.erb
<% content_for :title do %>
	Contact
<% end %>

<div id="contact_left">
	<h5>Both Offices</h5>
	<p>
		Tel. 415.839.8779 <br/>
		Fax. 415.376.0956
	</p>
	<div class="locations_list">
		<div class="location">
			<div class="location_details">
				<p>
					<span class="location_title">San Francisco</span><br/>
					580 California Street <br/>
					Suite 1600 <br/>
					San Francisco, CA  94104
				</p>
				<p>
					<a href="http://maps.google.com/maps?saddr=&daddr=580%20california%20street,%20san%20francisco,%20ca">Get Directions</a>
				</p>
			</div>
			<div class="location_map" id="sf_map"></div>
		</div>
		<div class="location">
			<div class="location_details">
				<p>
					<span class="location_title">Walnut Creek</span><br/>
					2175 N. California Blvd.<br/>
					Suite 805 <br/>
					Walnut Creek, CA 94596
				</p>
				<p>
					<a href="http://maps.google.com/maps?saddr=&daddr=2175%20n.%20california%20blvd,%20walnut%20creek,%20ca">Get Directions</a>
				</p>
			</div>
			<div class="location_map" id="wc_map"></div>
		</div>
	</div> 
</div>

<div id="contact_right">
	<h5>Attorneys</h5>
	<div class="contact_list">
	<% @employees.each do |employee |%>
		<div class="contact">
			<div class="contact_photo">
				<%= image_tag ('biopics/' + employee.initials.downcase + 'thumb.jpg'), :height => '80px;' %>
			</div>
			<div class="contact_details">
				<span class="contact_name"><%= employee.full_name %></span> <br/>
				<a href="mailto:<%= employee.email %>"><%= employee.email %></a><br/>
				Direct: <%= employee.direct_number %>
			</div>
		</div>
	<% end %>
	</div>
</div>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :display_order %><br />
    <%= f.text_field :display_order %>
  </div>
  <div class="field">
    <%= f.label :short_bio %><br />
    <%= f.text_area :short_bio %>
  </div>
  <div class="field">
    <%= f.label :full_bio %><br />
    <%= f.text_area :full_bio %>
  </div>
<div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
<div class="field">
    <%= f.label :direct_number %><br />
    <%= f.text_field :direct_number %>
  </div>
<div class="field">
    <%= f.label :role %><br />
    <%= f.text_field :role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Middle name</th>
	<th>Display Order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.first_name %></td>
    <td><%= employee.last_name %></td>
    <td><%= employee.middle_name %></td>
	<td><%= employee.display_order %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<% content_for :title do %>
	<%= link_to "Attorneys", attorneys_path %> <span style="font-size:.8em; padding:0 3px;">></span> <%= @employee.full_name %> 
<% end %>
<div class="employee">
	<div class="photo">
		<%= image_tag ('biopics/' + @employee.initials.downcase + 'thumb.jpg') %>
	</div>
	<div class="short_bio">
		<div class="name">
			<a href="#" class="link_to_full_bio"><%= @employee.full_name %></a>
		</div>
		<%= raw @employee.short_bio %> <br />
		<%= raw @employee.full_bio %>
	</div>
</div>

app/views/home/index.html.erb
<% content_for :title do %>
	About The Firm
<% end %>

<p style="text-indent:40px;">
	Putterman Logan &amp; Giles LLP brings talent and a rich depth of experience to its clients’ legal matters.  Formed in January 2006 by William A. Logan, Jr. (USF ’84, J.D., cum laude) and Anthony D. Giles (Boalt, ’95, J.D.), who practiced law together in the 1990’s at the San Francisco firm of Lasky, Haas &amp; Cohler, Logan &amp; Giles LLP is a complex civil litigation firm that knows how to achieve results.  In August 2011, Don Putterman, who had worked with William Logan at Pillsbury Winthrop (formerly Pillsbury, Madison &amp; Sutro), joined the firm.  Unlike many “specialists”, we recognize that every client and every case is unique and each client has its own needs and goals.  We pride ourselves on quickly mastering the factual and legal issues presented by each case and implementing creative and winning strategies to accomplish our clients’ goals.</p>
	<p style="text-indent:40px;">PLG lawyers are tenacious, and aggressive when necessary to deal with an undisciplined opponent, but always consistent with the client’s objective in the litigation.  We also understand that clients first and foremost want and are entitled to cost-effective representation and resolution.  
</p>
<p>
	<%= link_to 'BASF - Senior Partners Opening Their Own Firms', 'DJPArticle.pdf' %> 
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plg</title>
	<%= stylesheet_link_tag    "application" %>
	<%= stylesheet_link_tag    "StyleSheet" %>
	<%= javascript_include_tag "application" %>
	<%= javascript_include_tag "jquery.corner" %>
	<%= javascript_include_tag "popup" %>
	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyA2-ed7OmmwifGLjduTYIMB4ffqGv8Ohxc&sensor=false"></script>
	<%= csrf_meta_tags %>
</head>
<body onload="initialize()">
	<div id="container">
        <div id="logo_header">
            <%= image_tag "logolarge.png", :id => 'logo' %>
        </div>
        <div id="navbackground">
            <div id="nav">
                <ul>
                    <li><%= link_to "THE FIRM", "/home" %></li>
					<li><%= link_to "ATTORNEYS", "/attorneys" %></li>
					<li><%= link_to "CONTACT", "/contact" %></li>
                </ul>
            </div>
        </div>
        <div id="main">
            <div id="main_right">
                <h4>
					<%= yield :title %>
                </h4>
                <div class="main_body">
					<%= yield %>
                </div>
            </div>
        </div>
		<div id="footer">
            <div id="footer_left">
                &copy Putterman Logan & Giles 2011</div>
            <div id="footer_right">
            </div>
        </div>
        <div style="clear: both;">
        </div>
    </div>
</body>
</html>